name: halloween_game
description: Interactive Halloween Game with Spooky Objects

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1        # For sound effects and background music

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Add sound assets here
  assets:
    - assets/sounds/
    - assets/images/